---
abstract: 'Create DTrace providers for Perl programs.'
author:
  - 'Chris Andrews <chris@nodnol.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-DTrace-Provider
no_index:
  directory:
    - t
    - inc
requires:
  Sub::Exporter: 0
version: 1.03
